---
- name: test play
  hosts: servera
  tasks:
  - name: print os info
    ansible.builtin.shell:
      cmd: cat /etc/os-release >> os.txt
  - name: update everything
    community.general.zypper:
      name: '*'
      state: latest
