---
- name: test play
  hosts: servera
  become: yes
  tasks:
  - name: print os info
    ansible.builtin.shell:
      cmd: cat /etc/os-release >> os.txt
  - name: update everything
    ansible.builtin.dnf:
      name: '*'
      state: latest
